import { createSlice } from '@reduxjs/toolkit'

const anecdoteSlice = createSlice({
  name: 'anecdotes',
  initialState: [
    { content: 'If it hurts, do it more often', votes: 0, id: 1 },
    { content: 'Adding manpower to a late software project makes it later!', votes: 0, id: 2 },
  ],
  reducers: {
    voteFor(state, action) {
      const id = action.payload
      const anecdoteToVote = state.find(a => a.id === id)
      if (anecdoteToVote) {
        anecdoteToVote.votes += 1
      }
      // Sort by votes in descending order
      state.sort((a, b) => b.votes - a.votes)
    },
    addAnecdote(state, action) {
      const newAnecdote = {
        content: action.payload,
        votes: 0,
        id: Math.floor(Math.random() * 1000000)
      }
      state.push(newAnecdote)
    }
  }
})

// Export action creators automatically generated by createSlice
export const { voteFor, addAnecdote } = anecdoteSlice.actions

// Export the reducer for store.js
export default anecdoteSlice.reducer
